cqfd: parser: move error to config_load()
This moves the error handling to the caller.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -77,10 +77,6 @@ EOF
 cfg_parser() {
 	local ini
 
-	if [ ! -f "$1" ]; then
-		die "Unable to find $1 - create it or pick one using 'cqfd -f'"
-	fi
-
 	mapfile -t ini <"$1"                                 # convert to line-array
 	ini=("${ini[@]//[/\\[}")                             # escape [
 	ini=("${ini[@]//]/\\]}")                             # escape ]
@@ -94,10 +90,7 @@ cfg_parser() {
 	ini+=("}")                                           # add the last brace
 	ini[0]="${ini[0]/\}/}"                               # remove the first brace
 	ini=("$(printf "%s\n" "${ini[@]}")")                 # reconvert to line-array
-	if ! eval "${ini[*]}"; then                          # eval the result
-		debug "$1: fail to evaluate shell:" "${ini[@]}"
-		die "$1: Invalid ini-file!"
-	fi
+	eval "${ini[*]}"                                     # eval the result
 }
 
 ## die() - exit when an error occured
@@ -522,7 +515,13 @@ config_load() {
 		local cqfdrc_dir="$cqfd_project_dir/"
 	fi
 
-	cfg_parser "${cqfdrc_dir}${cqfdrc}"
+	if [ ! -f "${cqfdrc_dir}${cqfdrc}" ]; then
+		die "Unable to find ${cqfdrc_dir}${cqfdrc} - create it or pick one using 'cqfd -f'"
+	fi
+
+	if ! cfg_parser "${cqfdrc_dir}${cqfdrc}"; then
+		die "${cqfdrc_dir}${cqfdrc}: Invalid ini-file!"
+	fi
 
 	# generate dynamically the list of flavors based on the names of shell
 	# functions reported by the buildtin:
