cqfd: add warning if run -c with build.command unset
The commit 32e5b07b9cd89243b5fb2410ad5dcc4fbf1dbe4e introduced a minor
regression that was fixed by f75b42a7a84a40fbb55aa13c78b619157921c574.

This adds a warning if the build.command is unset and the command run -c
is used to tell the user it concatenates the argument to nothing.

This fixes commit 32e5b07b9cd89243b5fb2410ad5dcc4fbf1dbe4e.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -93,6 +93,12 @@ cfg_parser() {
 	eval "${ini[*]}"                                     # eval the result
 }
 
+## warn() - output warning
+# $* messages and variables shown in the message
+warn() {
+	echo "cqfd: warning: $*" >&2
+}
+
 ## die() - exit when an error occured
 # $* messages and variables shown in the error message
 die() {
@@ -681,6 +687,10 @@ while [ $# -gt 0 ]; do
 		if [ "$1" = "-c" ]; then
 			if [ "$#" -lt 2 ]; then
 				die "option -c requires arguments"
+			fi
+
+			if [ -z "$build_cmd" ]; then
+				warn "$cqfdrc: Missing or empty build.command property"
 			fi
 
 			shift
