automatically search for project directory upwards
In certain situations, it can be challenging to use cqfd when working
from a sub-directory within our project. To address this, search for a
configuration context by checking the parent directory hierarchy,
similar to how git and other tools operate.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -210,7 +210,7 @@ docker_run() {
 	       --log-driver=none \
 	       -v "$tmp_launcher":/bin/cqfd_launch \
 	       -v ~/.ssh:"$cqfd_user_home"/.ssh \
-	       -v "$PWD":"$cqfd_user_cwd" \
+	       -v "$cqfd_project_dir":"$cqfd_project_dir" \
 	       ${home_env_var:+ -e "$home_env_var"} \
 	       $interactive_options \
 	       ${SSH_AUTH_SOCK:+ -v $SSH_AUTH_SOCK:"$cqfd_user_home"/.sockets/ssh} \
@@ -355,10 +355,34 @@ EOF
 	echo $tmpfile
 }
 
+# locate_project_dir() - locate directory with .cqfd upwards
+# The directory will be printed on stdout, if found.
+locate_project_dir() {
+	local search_dir="$PWD"
+
+	while [ "$search_dir" != "/" ]; do
+		if [ -d "$search_dir"/"$cqfddir" ]; then
+			realpath "$search_dir"
+			return 0
+		fi
+		search_dir="$(readlink -f "$search_dir"/..)"
+	done
+
+	return 1
+}
+
 # config_load() - load build settings from cqfdrc
 # $1: optional "flavor" of the build, is a suffix of command.
 config_load() {
-	IFS="$IFS" parse_ini_config_file "$cqfdrc"
+	if ! cqfd_project_dir=$(locate_project_dir); then
+		die ".cqfd directory not found in directory tree"
+	fi
+
+	if ! $has_custom_cqfdrc; then
+		local cqfdrc_dir="$cqfd_project_dir/"
+	fi
+
+	IFS="$IFS" parse_ini_config_file "${cqfdrc_dir}${cqfdrc}"
 
 	cfg.section.project # load the [project] section
 	project_org="$org"
@@ -386,7 +410,7 @@ config_load() {
 	release_transform="$tar_transform"
 	release_tar_opts="$tar_options"
 
-	dockerfile="${cqfddir}/${distro:-docker}/Dockerfile"
+	dockerfile="${cqfd_project_dir}/${cqfddir}/${distro:-docker}/Dockerfile"
 
 	if [ -z "$project_org" ] || [ -z "$project_name" ]; then
 		die "Please set project.org and project.name in .cqfdrc"
@@ -407,6 +431,7 @@ config_load() {
 	fi
 }
 
+has_custom_cqfdrc=false
 has_to_release=false
 while [ $# -gt 0 ]; do
 	case "$1" in
@@ -438,6 +463,7 @@ while [ $# -gt 0 ]; do
 		;;
 	-f)
 		shift
+		has_custom_cqfdrc=true
 		cqfdrc="$1"
 		;;
 	-C)
