cqfd: parser: allow to parse an empty ini file
This patch makes the parser smarter. It allows the parser to not fail
when it evaluates an empty ini file.

Instead, cqfd fails when it is about to use data from the cqfdrc that
are missing.

This is an example when the cqfdrc file is empty (using /dev/null).

Before this patch, cqfd was complaining about an invalid ini-file:

	$ cqfd -f /dev/null
	cqfd: fatal: /dev/null: Invalid ini-file!

... which does not help that much about the failure.

Now, it complains about a missing section:

	$ cqfd -f /dev/null
	cqfd: fatal: /dev/null: Missing project section!

... which may help the user to know what is going wrong.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -94,8 +94,8 @@ parse_ini_config_file() {
 	ini=( "${ini[@]/%\)/) {}" )                  # the multiline trick
 	ini=( "${ini[@]/%\( \)/\(\) \{}" )           # convert text2function (2)
 	ini=( "${ini[@]/%\} \)/\}}" )                # remove extra parenthesis
-	ini[0]="${ini[0]/\}/}"                       # remove the first brace
 	ini+=( "}" )                                 # add the last brace
+	ini[0]="${ini[0]/\}/}"                       # remove the first brace
 	ini=("$(printf "%s\n" "${ini[@]}")")         # reconvert to line-array
 	if ! eval "${ini[*]}"; then                  # eval the result
 		debug "$1: fail to evaluate shell:" "${ini[@]}"
@@ -539,7 +539,11 @@ config_load() {
 		fi
 	done
 
-	cfg.section.project # load the [project] section
+	# load the [project] section
+	if ! cfg.section.project 2>/dev/null; then
+		die "$cqfdrc: Missing project section!"
+	fi
+
 	# shellcheck disable=SC2154
 	project_org="$org"
 	# shellcheck disable=SC2154
@@ -554,7 +558,11 @@ config_load() {
 		die "$cqfdrc: Missing project.org or project.name properties"
 	fi
 
-	cfg.section.build # load the [build] section
+	# load the [build] section
+	if ! cfg.section.build 2>/dev/null; then
+		die "$cqfdrc: Missing build section!"
+	fi
+
 	build_flavors="${flavors[*]}"
 
 	# build parameters may be overriden by a flavor defined in the
@@ -562,7 +570,10 @@ config_load() {
 	local flavor="$1"
 	if [ -n "$flavor" ]; then
 		if grep -qw "$flavor" <<< "${flavors[*]}"; then
-			cfg.section."$flavor" # load the [$flavor] section
+			# load the [$flavor] section
+			if ! cfg.section."$flavor" 2>/dev/null; then
+				die "$cqfdrc: Missing $flavor section!"
+			fi
 		else
 			die "flavor \"$flavor\" not found in flavors list"
 		fi
