Fix "cqfd: add warning if run -c with build.command unset"
The .cqfdrc file is not loaded and the warning below always poutputs
even if command= is set to an non-empty string:

	$ cat .cqfdrc
	[project]
	name=test
	org=test
	[build]
	command=true

	$ cqfd run -c true
	cqfd: warning: .cqfdrc: Missing or empty build.command property

This fixes commit 6dd7415ac41376aafc0581237ebbd1647d420bcb.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -686,10 +686,6 @@ while [ $# -gt 0 ]; do
 				die "option -c requires arguments"
 			fi
 
-			if [ -z "$build_cmd" ]; then
-				warn "$cqfdrc: Missing or empty build.command property"
-			fi
-
 			shift
 			break
 		fi
@@ -724,6 +720,10 @@ while [ $# -gt 0 ]; do
 done
 
 config_load "$flavor"
+
+if ! $has_alternate_command && [ -n "$*" ] && [ -z "$build_cmd" ]; then
+	warn "$cqfdrc: Missing or empty build.command property"
+fi
 
 if $has_alternate_command; then
 	build_cmd="$*"
