custom_img_name: cleanup code + documentation

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -120,6 +120,12 @@ docker_build() {
 	fi
 }
 
+# image_exists_locally(): checks if image exists in the local image store
+# arg$1: the image name to check
+image_exists_locally() {
+	docker image inspect "$1" &> /dev/null
+}
+
 # docker_run() - run command in configured container
 # A few implementation details:
 #
@@ -137,10 +143,15 @@ docker_build() {
 #
 docker_run() {
 
-	if ! docker image inspect $docker_img_name &> /dev/null; then
+	if ! image_exists_locally "$docker_img_name"; then
 		# If custom image name is used, try to pull it before dying
-		[ -n "$custom_img_name" ] && docker pull $docker_img_name
-		[ $? -ne 0 ] && die "The docker image doesn't exist, launch 'cqfd init' to create it"
+		if [ "$custom_img_name" ]; then
+			if ! docker pull "$docker_img_name" >& /dev/null; then
+				die "Custom image couldn't be pulled, please build/upload it first"
+			fi
+		else
+			die "The docker image doesn't exist, launch 'cqfd init' to create it"
+		fi
 	fi
 
 	local interactive_options
@@ -450,8 +461,8 @@ config_load() {
 		die "$dockerfile not found"
 	fi
 
-	if [ -n "$custom_img_name" ]; then
-		docker_img_name="${custom_img_name}"
+	if [ "$custom_img_name" ]; then
+		docker_img_name="$custom_img_name"
 	else
 		# This will look like cqfd_USER_ORG_NAME_HASH
 		local format_user=$(echo $USER | sed 's/[^0-9a-zA-Z\-]/_/g')
