quote user directory variables
Running commands would fail when one directory leading to CWD contained
spaces. This is solved by quoting every variable referring to one of
those paths.

This fixes #83.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -189,7 +189,7 @@ docker_run() {
 
 	# Set HOME variable for the $cqfd_user, except if it was
 	# explicitely set via CQFD_EXTRA_RUN_ARGS
-	local home_env_var="-e HOME=$cqfd_user_home"
+	local home_env_var="HOME=$cqfd_user_home"
 	if echo "$CQFD_EXTRA_RUN_ARGS" | egrep -q "(-e[[:blank:]]*|--env[[:blank:]]+)HOME="; then
 		home_env_var=""
 	fi
@@ -202,13 +202,13 @@ docker_run() {
 	       $CQFD_EXTRA_RUN_ARGS \
 	       --rm \
 	       --log-driver=none \
-	       -v $tmp_launcher:/bin/cqfd_launch \
-	       -v ~/.ssh:$cqfd_user_home/.ssh \
-	       -v "$PWD":$cqfd_user_cwd \
-	       $home_env_var \
+	       -v "$tmp_launcher":/bin/cqfd_launch \
+	       -v ~/.ssh:"$cqfd_user_home"/.ssh \
+	       -v "$PWD":"$cqfd_user_cwd" \
+	       ${home_env_var:+ -e "$home_env_var"} \
 	       $interactive_options \
-	       ${SSH_AUTH_SOCK:+ -v $SSH_AUTH_SOCK:$cqfd_user_home/.sockets/ssh} \
-	       ${SSH_AUTH_SOCK:+ -e SSH_AUTH_SOCK=$cqfd_user_home/.sockets/ssh} \
+	       ${SSH_AUTH_SOCK:+ -v $SSH_AUTH_SOCK:"$cqfd_user_home"/.sockets/ssh} \
+	       ${SSH_AUTH_SOCK:+ -e SSH_AUTH_SOCK="$cqfd_user_home"/.sockets/ssh} \
 	       $docker_img_name cqfd_launch "$@" 2>&1
 }
 
@@ -320,7 +320,7 @@ test -n "\$failed" &&
 groupadd -og $GROUPS -f builders || die "groupadd command failed."
 useradd -s /bin/bash -ou $UID -g $GROUPS -d "$cqfd_user_home" $cqfd_user \
 	|| die "useradd command failed."
-chown $UID:$GROUPS $cqfd_user_home || die "chown command failed."
+chown $UID:$GROUPS "$cqfd_user_home" || die "chown command failed."
 
 # Add specified groups to cqfd_user
 for g in ${CQFD_GROUPS}; do
@@ -336,7 +336,7 @@ for g in ${CQFD_GROUPS}; do
 done
 
 # run the provided command in the working directory
-cd $cqfd_user_cwd || die "Changing directory to \"$cqfd_user_cwd\" failed."
+cd "$cqfd_user_cwd" || die "Changing directory to \"$cqfd_user_cwd\" failed."
 if [ -n "\$has_sudo" ]; then
 	# Use sudo to provide a controlling TTY for the executed command
 	debug "Using \"sudo\" to execute command \"\$@\" as user \"$cqfd_user\""
