cqfd: allow cqfd to run without a dockerfile
When using a prebuilt distant docker image, cqfd run will now work when
used with no local dockerfile.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -122,6 +122,11 @@ docker_build() {
 		args+=(--quiet)
 	fi
 
+	# If custom image name is used, it is pulled pull by docker_run()
+	if [ "$project_image" ]; then
+		return
+	fi
+
 	# Append extra args from the .cqfdrc [build] section
 	if [ "$build_docker_build_args" ]; then
 		local array
@@ -139,7 +144,7 @@ docker_build() {
 	fi
 
 	# Name the resulting image
-	args+=(--tag "$docker_img_name")
+	args+=(--tag "$cqfd_image")
 
 	# Set the context
 	if [ -z "$project_build_context" ]; then
@@ -177,10 +182,10 @@ docker_run() {
 	local args=(--privileged)
 
 	# The image does not exist
-	if ! image_exists_locally "$docker_img_name"; then
+	if ! image_exists_locally "$cqfd_image"; then
 		# If custom image name is used, try to pull it before dying
-		if [ "$project_custom_img_name" ]; then
-			if ! "$cqfd_docker" pull "$docker_img_name" &>/dev/null; then
+		if [ "$project_image" ]; then
+			if ! "$cqfd_docker" pull "$cqfd_image" &>/dev/null; then
 				die "Custom image couldn't be pulled, please build/upload it first"
 			fi
 		else
@@ -256,6 +261,11 @@ docker_run() {
 		die "CQFD_EXTRA_PORTS is no more supported, use" \
 		    "CQFD_EXTRA_RUN_ARGS=\"-p <host_port>:<docker_port>\""
 	fi
+	if [ -n "$project_custom_img_name" ]; then
+		die "custom_img_name is no more supported, use" \
+		    "either tag to name your image or image to pull an image" \
+		    "from a registry."
+	fi
 
 	# The user may set the user_extra_groups in the .cqfdrc
 	# file to add groups to the user in the container.
@@ -314,7 +324,7 @@ docker_run() {
 	args+=(--entrypoint "/bin/cqfd-entrypoint")
 
 	# Set positional arguments
-	args+=("$docker_img_name" "$1")
+	args+=("$cqfd_image" "$1")
 
 	# Run command
 	debug executing: "$cqfd_docker" run "${args[@]}"
@@ -559,6 +569,10 @@ load_config() {
 	project_build_context="$build_context"
 	# shellcheck disable=SC2154
 	project_custom_img_name="$custom_img_name"
+	# shellcheck disable=SC2154
+	project_tag="$tag"
+	# shellcheck disable=SC2154
+	project_image="$image"
 
 	# check for [project] org and name properties are set and are not empty
 	if [ -z "$project_org" ] || [ -z "$project_name" ]; then
@@ -605,22 +619,40 @@ load_config() {
 	# shellcheck disable=SC2154
 	release_tar_opts="$tar_options"
 
-	dockerfile="$cqfd_project_dir/$cqfddir/${build_distro:-docker}/Dockerfile"
-	if [ ! -f "$dockerfile" ]; then
-		die "$dockerfile not found"
-	fi
+	cqfd_image="$project_image"
+	if [ ! "$cqfd_image" ]; then
+		local Un 
+		local Po
+		local Pn
+		local Dh
+		local DH
+		local Bd
 
-	if [ "$project_custom_img_name" ]; then
-		docker_img_name="$project_custom_img_name"
-	else
-		local format_user
-		local dockerfile_hash
+		dockerfile="$cqfd_project_dir/$cqfddir/${build_distro:-docker}/Dockerfile"
+		if [ ! -f "$dockerfile" ]; then
+			die "$dockerfile not found"
+		fi
 
-		# This will look like cqfd_USER_ORG_NAME_HASH
 		# shellcheck disable=SC2001
-		format_user=$(sed 's/[^0-9a-zA-Z\-]/_/g' <<<"$USER")
-		dockerfile_hash=$(sha256sum "$dockerfile" | cut -b 1-7)
-		docker_img_name="cqfd${format_user:+_$format_user}_${project_org}_${project_name}_${dockerfile_hash}${build_distro:+_$build_distro}"
+		Un=$(sed 's/[^0-9a-zA-Z\-]/_/g' <<<"$USER")
+		Po="$project_org"
+		Pn="$project_name"
+		Dh=$(sha256sum "$dockerfile" | cut -b 1-7)
+		DH=$(sha256sum "$dockerfile" | cut -b 1-64)
+		Bd="${build_distro:-docker}"
+		if ! [ "$project_tag" ]; then
+			project_tag="cqfd_%Un_%Po_%Pn_%Dh"
+			if [ "$build_distro" ]; then
+				project_tag+="_%Bd"
+			fi
+		fi
+		# shellcheck disable=SC2001
+		cqfd_image=$(sed -e 's!%Un!'"$Un"'!g;
+			             s!%Po!'"$Po"'!g;
+			             s!%Pn!'"$Pn"'!g;
+			             s!%Dh!'"$Dh"'!g;
+			             s!%DH!'"$DH"'!g;
+			             s!%Bd!'"$Bd"'!g;' <<<"$project_tag")
 	fi
 }
 
