cqfd: style fixup
Fixup style in cqfd to favor readability.

- Only use {} around variables when variables need to be protected or
  using special functions. Avoids WTF situations like ${$1}.
- Make same-line control constructs consistent (for..do, while..do)
- Fixup case blocks indentation
- Fixup strings and line lengths to favor readability

Also add a few grammar fixes.

Change-Id: Ib2062ef8d1dcc179f82568126abd317f44a543b6

diff --git a/common/sfl/cqfd b/common/sfl/cqfd
--- a/common/sfl/cqfd
+++ b/common/sfl/cqfd
@@ -1,5 +1,4 @@
-#! /bin/bash -
-
+#!/bin/bash
 #
 # Copyright (C) 2015 Savoir-faire Linux, Inc.
 #
@@ -11,14 +10,14 @@ ESUCCESS=0
 
 PROGNAME=`basename $0`
 
-## usage() - print the usage in stdin
+## usage() - print usage on stdin
 usage() {
 cat << EOF
-Usage: ${PROGNAME} [OPTIONS]
+Usage: $PROGNAME [OPTIONS]
 
-* If you have a .sflproject: ${PROGNAME}
-* If you want to build with a special command: ${PROGNAME} -b <"CMD">
-* If you want default build command: ${PROGNAME} <OPTIONS>
+* If you have a .sflproject: $PROGNAME
+* If you want to build with a special command: $PROGNAME -b <"CMD">
+* If you want default build command: $PROGNAME <OPTIONS>
 
 Options are:
 	-m <buildroot | yocto | openwrt>    Model of build system to use.
@@ -39,25 +38,28 @@ EOF
 # $@ messages and variables shown in the error message
 die() {
 	echo "Fatal: $@" 1>&2
-	exit ${EERROR}
+	exit $EERROR
 }
 
 #docker_build() - Initialize build container
 # $1 docker image name
 docker_build() {
-	docker build -t "${$1}" docker/.
+	docker build -t "$1" docker/.
 }
 
 ## docker_run() - run command in configured container
 docker_run() {
-	if  [ "${BUILD_DOCKER}" = "1" ]; then
-		docker_build "${DOCKER_IMG_NAME}"
+	if  [ "$BUILD_DOCKER" = "1" ]; then
+		docker_build "$DOCKER_IMG_NAME"
 	fi
-	docker run --privileged -v "${PROJECT_PATH}":/home/builder/src -v ~/.ssh:/home/builder/.ssh \
-	-v `dirname $SSH_AUTH_SOCK`:/home/builder/.sockets -it \
-		"${DOCKER_IMG_NAME}" /bin/bash -c "groupadd -og ${GROUPS} -f builders && \
-		                useradd -s /bin/bash -u ${UID} -g ${GROUPS} builder && \
-				su - builder -c \"cd src/ && $1\""
+
+	docker run --privileged -v "$PROJECT_PATH":/home/builder/src \
+	       -v ~/.ssh:/home/builder/.ssh \
+	       -v `dirname $SSH_AUTH_SOCK`:/home/builder/.sockets \
+	       -it "$DOCKER_IMG_NAME" \
+	       /bin/bash -c "groupadd -og $GROUPS -f builders && \
+	       useradd -s /bin/bash -u $UID -g $GROUPS builder && \
+	       su - builder -c \"cd src/ && $1\""
 }
 
 PROJECT_PATH="${PWD%%/sfl}"
@@ -66,7 +68,7 @@ DISTRO_BUILD_PARAM=
 DOCKER_IMG_NAME=""
 BUILD_MODEL=
 DOCKER_FILE_PATH="./docker/"
-DOCKER_FILE=${DOCKER_FILE_PATH}"Dockerfile"
+DOCKER_FILE="$DOCKER_FILE_PATH/Dockerfile"
 SFL_PROJECT="../.sflproject"
 BUILD_CMD=
 RELEASE_FILES=
@@ -75,108 +77,113 @@ MAKE_ARCHIVE=0
 ### main ###
 
 # The .sflproject file allows per-project customizations
-if [ -f "${SFL_PROJECT}" ]; then
-	source "${SFL_PROJECT}"
+if [ -f "$SFL_PROJECT" ]; then
+	source "$SFL_PROJECT"
 fi
 
 # Compatibility with P_BUILD_CMD or P_RELEASE_FILE
-if [ -n "${P_BUILD_CMD}" ]; then
-	BUILD_CMD=${P_BUILD_CMD}
+if [ -n "$P_BUILD_CMD" ]; then
+	BUILD_CMD=$P_BUILD_CMD
 fi
 
-if [ -n "${P_RELEASE_FILES}" ]; then
-	RELEASE_FILES=${P_RELEASE_FILES}
+if [ -n "$P_RELEASE_FILES" ]; then
+	RELEASE_FILES=$P_RELEASE_FILES
 fi
 
-if [ -n "${P_BUILD_CONTAINER}" ]; then
+if [ -n "$P_BUILD_CONTAINER" ]; then
 	temp_path=${PWD%%/sfl}
 	DOCKER_IMG_NAME="${P_BUILD_CONTAINER}_${temp_path##*/}"
 else
         die "No value for P_BUILD_CONTAINER in .sflproject, client name wanted"
 fi
 
-while getopts "ijhp:m:b:g:" OPTION
-do
-	case "${OPTION}" in
-		h)
-			usage
-			exit ${ESUCCESS};;
-		m)
-			BUILD_MODEL="${OPTARG}";;
-		p)
-			DISTRO_BUILD_PARAM="${OPTARG}";;
-		b)
-			BUILD_CMD="${OPTARG}";;
-		g)
-			DOCKER_IMG_NAME="${OPTARG}";;
-		j)
-			MAKE_ARCHIVE=1;;
-		i)
-
-			BUILD_DOCKER=1;;
-		*)
-			die "Unknown parameter ${OPTION}";;
-
+while getopts "ijhp:m:b:g:" OPTION; do
+	case "$OPTION" in
+	h)
+		usage
+		exit $ESUCCESS
+		;;
+	m)
+		BUILD_MODEL="$OPTARG"
+		;;
+	p)
+		DISTRO_BUILD_PARAM="$OPTARG"
+		;;
+	b)
+		BUILD_CMD="$OPTARG"
+		;;
+	g)
+		DOCKER_IMG_NAME="$OPTARG"
+		;;
+	j)
+		MAKE_ARCHIVE=1
+		;;
+	i)
+		BUILD_DOCKER=1
+		;;
+	*)
+		die "Unknown parameter $OPTION"
+		;;
 	esac
 done
 
-if [ ! -f "${DOCKER_FILE}" ]; then
-	die " ${DOCKER_FILE} not found"
+if [ ! -f "$DOCKER_FILE" ]; then
+	die " $DOCKER_FILE not found"
 fi
 
-# BUILD_CMD can be taken from Dockerfile or you can choose your own with -b
-if [ -n "${BUILD_CMD}" ]; then
-	docker_run "${BUILD_CMD}"
+# BUILD_CMD can be taken from Dockerfile or you can choose your own
+# with -b
+if [ -n "$BUILD_CMD" ]; then
+	docker_run "$BUILD_CMD"
 else
-	if [ -z "${DISTRO_BUILD_PARAM}" ]; then
-		die "build parameters not specified. Use -p to specify a build \
-parameter"
+	if [ -z "$DISTRO_BUILD_PARAM" ]; then
+		die "build parameters not specified." \
+		    "Use -p to specify a build parameter"
 	fi
-	case "${BUILD_MODEL}" in
-		buildroot)
-			 BUILD_CMD="\
-make clean \
-&& make ${DISTRO_BUILD_PARAM} \
-&& make"
-			;;
 
-		yocto)
-			BUILD_CMD="
-set -e \
-&& source oe-init-build-env build-${DISTRO_BUILD_PARAM} \
-&& bitbake -f ${DISTRO_BUILD_PARAM}"
-			;;
+	case "$BUILD_MODEL" in
+	buildroot)
+		BUILD_CMD="make clean && make $DISTRO_BUILD_PARAM && make"
+		;;
 
-		openwrt)
-			BUILD_CMD="
-make clean \
-&& echo ${DISTRO_BUILD_PARAM} > .config \
-&& make defconfig \
-&& make"
-			;;
-		*)
-			die "build model not recognized"
+	yocto)
+		BUILD_CMD="set -e && \
+			source oe-init-build-env build-$DISTRO_BUILD_PARAM && \
+			bitbake -f $DISTRO_BUILD_PARAM"
+		;;
+
+	openwrt)
+		BUILD_CMD="make clean && \
+			echo $DISTRO_BUILD_PARAM >.config && \
+			make defconfig && \
+			make"
+		;;
+	*)
+		die "build model not recognized"
+		;;
 	esac
-	docker_run "${BUILD_CMD}"
+
+	docker_run "$BUILD_CMD"
 fi
 
-if [ "${MAKE_ARCHIVE}" = "1" ]; then
 # Create Release package
+if [ "$MAKE_ARCHIVE" = "1" ]; then
 	if [ -z "$JOB_NAME" ]; then
 		JOB_NAME="local-build"
 		BUILD_ID="`date --rfc-3339='date'`"
 	fi
+
 	if [ -z "$RELEASE_FILES" ]; then
-		die "No files to put in archive, check RELEASE_FILE variable \
-		in $SFL_PROJECT"
+		die "No files to archive, check RELEASE_FILE in $SFL_PROJECT"
 	fi
-	for file in $RELEASE_FILES;
-	do
-		[ -f $file ] || die "Cannot create release: $file missing"
+
+	for file in $RELEASE_FILES; do
+		[ -f $file ] || die "Cannot create release: missing $file"
 	done
 
 	RELEASE_PACKAGE=${JOB_NAME}_${BUILD_ID}.tar.xz
 	XZ_OPT=-9 tar --transform "s/.*\///g" -cJf \
 		$RELEASE_PACKAGE $RELEASE_FILES
 fi
-exit ${ESUCCESS}
+
+exit $ESUCCESS
